// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_j6eDg5MWSFJQ1ZWA-ElNDVq5vhzlBK0',
    appId: '1:841305894280:web:6416ddff5cd8098aaade3d',
    messagingSenderId: '841305894280',
    projectId: 'e-learning-a0247',
    authDomain: 'e-learning-a0247.firebaseapp.com',
    storageBucket: 'e-learning-a0247.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArp7atsV0nhsNi-7kLbhHDXZyGkWsjo4s',
    appId: '1:841305894280:android:551a52f23220aaaeaade3d',
    messagingSenderId: '841305894280',
    projectId: 'e-learning-a0247',
    storageBucket: 'e-learning-a0247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAae5oueUOgwGTXoNRZVDHob5qX2Ul8y9A',
    appId: '1:841305894280:ios:0f6612bac494d794aade3d',
    messagingSenderId: '841305894280',
    projectId: 'e-learning-a0247',
    storageBucket: 'e-learning-a0247.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAae5oueUOgwGTXoNRZVDHob5qX2Ul8y9A',
    appId: '1:841305894280:ios:0f6612bac494d794aade3d',
    messagingSenderId: '841305894280',
    projectId: 'e-learning-a0247',
    storageBucket: 'e-learning-a0247.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_j6eDg5MWSFJQ1ZWA-ElNDVq5vhzlBK0',
    appId: '1:841305894280:web:2feae34b20efa64caade3d',
    messagingSenderId: '841305894280',
    projectId: 'e-learning-a0247',
    authDomain: 'e-learning-a0247.firebaseapp.com',
    storageBucket: 'e-learning-a0247.firebasestorage.app',
  );
}
